INSERT INTO USER(ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (1, 'sung', '123', 'sungjin', 'sung@naver.com', CURRENT_TIMESTAMP());
INSERT INTO USER(ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (2, 'hong', '123', 'hong', 'hong@naver.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES (1, 1, 'TEST TITLE', 'TEST CONTENTS', CURRENT_TIMESTAMP(), 0);